### PR TITLE
fix feat command

### PR DESCRIPTION
**Pull request by ldm314**
The feat command was not working on my system. An old hardware device I have that required AUTH TLS to be support would disconnect immediately after issuing FEAT because FEAT was not returning the correct result.

### CODE REVIEW

**Comment by trs** [comment]
Thanks for the contribution.
Looks like this removes the default `UTF8` feature, and requires the registry on call instead of on start up.
Was the `UTF8` causing the issue on the older hardware?
Can you give me an example of a bad `FEAT` response and a corrected one? 
I'm just not sure what the fix is here. The feat should already respond with [`AUTH TLS`](https://github.com/autovance/ftp-srv/blob/master/src/commands/registration/auth.js#L18), does it not?

**Comment by ldm314** [comment]
It looks like I missed the UTF8 feat in adding the code. The requiring of the registry call on startup was not returning any results at all, requiring the registry on the call did work. I am not sure why it wasn't loading properly on startup. That was the main fix, to move the require statement. The feat command was returning a blank list.

I'll set up a test today and capture the results. We ended up not using ftp-srv in the end, having the ftp-srv in the same node server that was triggering the requests ends up in a deadlock.

**Comment by trs** [comment]
Thanks for clarifying!
I'm assuming the cyclical nature of this dependency is what's causing this to be empty.
I've put the core fix in https://github.com/autovance/ftp-srv/pull/238 along with a test.
Thanks again

**Comment by ldm314** [comment]
I retract my last statement "We ended up not using ftp-srv in the end," Still waking up after the new year :D I ended up separating out ftp-srv into it's own node process running only ftp-srv.

**Pull request closed without merging**
