### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Slender1808**

### CODE REVIEW

**Comment by matt-forster** [comment]
We don't use deepcode right now - if you could provide an argument as to why we should include this badge, that'd be great - it is hard to justify adding something with little to no description provided.

**Comment by Slender1808** [comment]
I believe that better than the description about DeepCode series shows the result of your analysis

Screenshot_20210609-123125_Chrome Dev

**Comment by Slender1808** [comment]
It's a tool I personally use in my projects, it always helps me with the code

**Comment by Slender1808** [comment]
Screenshot_20210609-123426_Chrome Dev

**Comment by matt-forster** [comment]
Sorry - we are well aware of the issues of the implementation of this module; legacy decisions and outdated Js patterns. We would welcome refactor pull requests, for sure! As for this doc feature, though it may provide valuable feedback, we are not interested in including this service in our readme as of right now.

Thanks for the suggestion, though!

**Pull request closed without merging**
